### ISSUE TITLE
Django 3 Support

### ISSUE THREAD

**Issue by yonatancohen** [Privex/django-mail-queue#7]
Will you add support for Django 3?

**Comment by yonatancohen** [comment]
Hi, any news regarding support Django 3?

**Comment by Someguy123** [comment]
I think this issue may have been resolved in pull request #8

It's merged and has been published as django-mail-queue 3.2.4 on PyPi.

Please upgrade the package with `pip3 install -U django-mail-queue` and let me know of any compatibility issues.
