### ISSUE TITLE
Un-generated mailqueue migration - Add to source control?

### ISSUE THREAD

**Issue by daveschaefer** [Privex/django-mail-queue#9]
Hello, it appears that mailqueue has a pending migration that has not been generated or added to source control. Would you be willing to add it?

Whenever I add django-mail-queue on a new project and run `manage.py`, I get the following message warning about it:

>$ python manage.py migrate
Operations to perform:
  Apply all migrations: ... mailqueue, ...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.`

I can manually generate this and apply it, and then the warning goes away:

>$ python manage.py makemigrations
Migrations for 'mailqueue':
  .../site-packages/mailqueue/migrations/0007_auto_20200316_1129.py
    - Alter field file_attachment on attachment
    - Alter field sent on mailermessage
    
>$ python manage.py migrate
Operations to perform:
  Apply all migrations: ... mailqueue, ...
Running migrations:
  Applying mailqueue.0007_auto_20200316_1129... OK

However, it would be great if this could be generated and added to the existing django-mail-queue package. Thanks!

**Comment by daveschaefer** [comment]
The generated migration looks like this:

`from django.db import migrations, models
import mailqueue.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0006_auto_20190815_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=mailqueue.utils.upload_to),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
    ]
`

**Comment by Someguy123** [comment]
I've generated the migration and added it to the repo 👍 

I've pushed out version 3.2.3 to PyPi with the new migration added - so you can simply `pip3 install -U django-mail-queue` and you'll get the migration

**Comment by daveschaefer** [comment]
Thank you very much! What a nice, fast reply :) Take care
